name: Android CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.28.0
        with:
          api-level: 29
          script: ./gradlew clean build connectedCheck jacocoFullReport
      - uses: codecov/codecov-action@v2.1.0
        with:
          files: ./build/reports/jacoco/jacocoFullReport.xml
          fail_ci_if_error: true
          verbose: true